kind: pipeline
name: winehq-novnc-baseimage

steps:
- name: docker
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: ich777/winehq-novnc-baseimage
    username: ich777
    password:
      from_secret: docker_password
    tags: latest